/**
 * --BLOCKS--
 * P = player
 * @ = portal
 * M = trampoline
 * b = normal block
 * _ = ice
 * # = lava
 * & = monster
 * % = cannon
 * -: Block of ice
 * X: Brick
 * A = Spike up
 * >: Spike right
 * <: Spike left
 * V: Spike down
 * ?: Mystery box
 * E: Acid
 * C: Mystery box that disappears
 * 17 max lines for y
 * 20 max lines for x
 */
/*
  [
    "                    ",
    "                    ",
    "                    ",
    "                    ",
    "                    ",
    "                    ",
    "                    ",
    "                    ",
    "                    ",
    "                    ",
    "                    ",
    "                    ",
    "                    ",
    "                    ",
    "                    ",
    "@                  P",
    "bbbbbbbbbbbbbbbbbbbb",
  ],
*/
var levels = [
  [
    "                    ",
    "                    ",
    "                    ",
    "                    ",
    "                    ",
    "                    ",
    "                    ",
    "                    ",
    "                    ",
    "                    ",
    "                    ",
    "                    ",
    "                    ",
    "                    ",
    "                    ",
    " @                 P",
    "bbbbbbbδδδδbbbbbbbbb",
    "++++++++++++++++++++",
  ],
  [
  '                    ',
  '                    ',
  '                   @',
  '                 bbb',
  '               b    ',
  '             b      ',
  '           b        ',
  '         b          ',
  '       b            ',
  '     b              ',
  '   b                ',
  '                    ',
  ' b                  ',
  '   b                ',
  '     b              ',
  '       b P          ',
  '#######bbb##########',
  'bbbbbbbbbbbbbbbbbbbb'
 ],
 [
  '              ',
  '              ',
  '              ',
  '              ',
  '              ',
  '              ',
  'P            @',
  'b            b',
  'CCCCCMCMCCCCCM',
  'CCMMCCCCCCMCCC',
  'CCCCCCMCMMCMCC',
  'CMCCMCCCCCCCCM',
  'CCCCCCCMMCCMCC',
  'CC?CCMCCCCMCCC',
  'bbCbbCbbCbbCbb',
  '??????????????'
 ],
 [
  '              b       ',
  '              b       ',
  '              bb@     ',
  '               bbM    ',
  '                      ',
  '                      ',
  '         M  A         ',
  '    V       bM        ',
  '             b      M ',
  '                      ',
  '                      ',
  '    M                 ',
  '                      ',
  '          M           ',
  '                  P   ',
  '                 bbb  ',
  '######################',
  'bbbbbbbbbbbbbbbbbbbbbb'
 ],
 [
  '                          ',
  '                          ',
  '         @                ',
  '         b                ',
  '             A            ',
  '                          ',
  '                          ',
  '                          ',
  '          A               ',
  'M                         ',
  '                          ',
  '                          ',
  'M                         ',
  '                          ',
  '                      P   ',
  'M   A        A       bb   ',
  '##########################',
  'bbbbbbbbbbbbbbbbbbbbbbbbbb'
 ],
 [
  '                         ',
  '     M                   ',
  '                         ',
  '                         ',
  '  A                      ',
  '                         ',
  '                         ',
  '                     bbbb',
  '      A            ##    ',
  '                   ##    ',
  '                   bb    ',
  '      -            bb    ',
  '                   bb    ',
  '    -              Pb    ',
  '      -             b    ',
  '                    b    ',
  '                    b    ',
  '         A        MMb   @',
  '#########################',
  'bbbbbbbbbbbbbbbbbbbbbbbbb'
 ],
 [
  '                       ',
  '     @                 ',
  '     #            M    ',
  '     #            M    ',
  '     #            M    ',
  '     #            #    ',
  '     #      --    #    ',
  '     #      MM    #    ',
  '     #            #    ',
  '     #            #    ',
  '     M            M    ',
  '                       ',
  '                       ',
  '     M     P      M    ',
  '                       ',
  '                       ',
  'A    M     A      M   A',
  'CCCCCCCCCC???CCCCCCCCCC',
  '#######################',
  'bbbbbbbbbbbbbbbbbbbbbbb'
 ],
 [
  '                         ',
  '                         ',
  '                         ',
  '                         ',
  '                         ',
  '                         ',
  '                         ',
  '                         ',
  '                         ',
  '                         ',
  '                         ',
  '                         ',
  '                         ',
  '                         ',
  '                         ',
  '@                       P',
  'δδbδbbδδδδδδbbδδδδδbδδbbb',
  'VVVVVVVVVVVVVVVVVVVVVVVVV',
  'EEE#EE##EE##EE##E##E#####',
  'bbbbbbbbbbbbbbbbbbbbbbbbb'
 ],
 [
  '@bVVVVVV                 ',
  ' bAAAAAAAAAAAAAAAAAAAAAAA',
  '     AAA                 ',
  'M M  A> A                ',
  '      A> A               ',
  '    M  >  A              ',
  '  M   M >  A             ',
  '    M    >  A            ',
  ' M   M M > AA            ',
  '     M   >  A            ',
  '    M   M A A            ',
  '          A  A           ',
  ' M     M  AAAAAAAAAAAAAAA',
  '        M   M            ',
  '  M  M                   ',
  '                         ',
  '           M      M      ',
  '                         ',
  '  M                      ',
  '    M   M    M   M    M  ',
  ' M         M            P',
  '                      MMM',
  '#########################',
  'bbbbbbbbbbbbbbbbbbbbbbbbb'
 ],
 [
  '                XX       ',
  '                > X      ',
  '                 AX      ',
  '                  X      ',
  '  X               X      ',
  '  X           XXX X      ',
  '  X            X  X      ',
  '  X     C      X  X      ',
  '  X            XM        ',
  '  X            XXM       ',
  '  X              V       ',
  '  X                      ',
  '      >                  ',
  '      >                  ',
  '@   A >         X        ',
  ' A    >         #        ',
  '    VVV         ?        ',
  '         ## <   C        ',
  '           M    ?        ',
  '           A    ?       P',
  '             M A A  δ  bb',
  'VVVVV###############+####',
  'AAAAAAAAAAAAAAAAAAAAAAAAA'
 ],
 [
  "                    ",
  "                    ",
  "                    ",
  "                    ",
  "                    ",
  "                    ",
  "                    ",
  "                    ",
  "                    ",
  "                    ",
  "                    ",
  "                    ",
  "                    ",
  "                    ",
  "                    ",
  "@                  P",
  "bbbbbbbbδδδδbbbbbbbb",
  "++++++++++++++++++++",
  "bbbbbbbbbbbbbbbbbbbb",
 ],
 [
  '                    ',
  '                    ',
  '                    ',
  '                    ',
  '                    ',
  '                    ',
  '                    ',
  '                    ',
  '                    ',
  '                    ',
  '                    ',
  '                    ',
  '                    ',
  '                    ',
  'δδ                 P',
  '@δ  &     &      δδb',
  '++++++++++++++++++++',
  'bbbbbbbbbbbbbbbbbbbb'
 ],
 [
  '         XX        VVV  ',
  '          X        > <  ',
  '          X         A   ',
  '         @X         A   ',
  '     A###bX             ',
  '     XXXXXX         A   ',
  '                        ',
  '  M  b              A   ',
  '                    A   ',
  '         X              ',
  '                  b A   ',
  '                b       ',
  '              δ         ',
  '          b             ',
  '            δ           ',
  '                        ',
  '          b             ',
  '        δ               ',
  '      b                 ',
  '                        ',
  '                        ',
  '       b                ',
  '                        ',
  '           b  P         ',
  '              b         ',
  '++++++++++++++++++++++++'
 ],
 [
  '                    ',
  '                    ',
  '                    ',
  '                    ',
  '                    ',
  '                    ',
  '                    ',
  '                    ',
  '                    ',
  '                    ',
  '                    ',
  '                    ',
  '                    ',
  '                    ',
  '                I   ',
  '@                  P',
  'bbbbbbbbbbbbbbbbbbbb'
 ],
 [
  '                    ',
  '                    ',
  '                    ',
  '                    ',
  '                    ',
  '                    ',
  '                    ',
  '                    ',
  '                    ',
  '                    ',
  '                    ',
  '                    ',
  '                    ',
  '                    ',
  '                    ',
  'P                  @',
  'bbbbbbbbbbbbbbbbbbbb'
 ],
[
  '                    ',
  '                    ',
  '                    ',
  '                    ',
  '                    ',
  '                    ',
  '                    ',
  '                    ',
  '                    ',
  '                    ',
  '                    ',
  '                    ',
  '                    ',
  '                    ',
  '                    ',
  '@                  P',
  'bbbbbbbb+++++bbbbbbb'
],
 [
  '                    ',
  '                    ',
  '                    ',
  '                    ',
  '                    ',
  '                    ',
  '                    ',
  '                    ',
  '                    ',
  '                    ',
  '                    ',
  '                    ',
  '                    ',
  '          I         ',
  '                    ',
  'P                  @',
  'bbbbbbbb+++++bbbbbbb'
 ],
 [
  '                    ',
  '                    ',
  '                    ',
  '                    ',
  '                    ',
  '                    ',
  '                    ',
  '                    ',
  '                    ',
  '                    ',
  '                    ',
  '                    ',
  '                    ',
  'ZZZZZZZZZZZZZZZZZZZZ',
  '                    ',
  '@                  P',
  'bbIIIIIIIIIIIIIIbbbb',
  '++++++++++++++++++++'
 ],
 [
  '                    ',
  '                    ',
  '                    ',
  '                    ',
  '                    ',
  '                    ',
  '                    ',
  '                    ',
  '                    ',
  '                    ',
  '            @       ',
  '            I       ',
  '             I      ',
  '            I       ',
  '                    ',
  '                   P',
  'bbbbbbbbbbbbbbbbbbbb'
 ],
[
  '                              ',
  '                              ',
  '                              ',
  '                              ',
  '                              ',
  '                              ',
  '                              ',
  '                              ',
  '                              ',
  '                              ',
  '                              ',
  '                              ',
  '           I                  ',
  '                              ',
  '@                            P',
  'bb                     t    bb',
  '++++++++++++++++++++++++++++++'
 ],
 [
  '                              ', 
  '            XX                ',
  '             X                ',
  '             X                ',
  '             X                ',
  '             XM     -         ',
  '             XV               ',
  '                              ',
  '                              ',
  '             -                ',
  '         -                    ',
  '                              ',
  '   -                          ',
  '                              ',
  '                              ',
  'P     -                       ',
  'b  -                         @',
  '++++++++++++++++++++++++++++++'
 ],
 [
  '                              ',
  '                              ',
  '                              ',
  '                              ',
  '                             +',
  '                             +',
  '                             +',
  '                             +',
  't                            +',
  '+                    +     @  ',
  'Xt                   X     X  ',
  '+                    +        ',
  '+                    +        ',
  '+                    +        ',
  'X                  t X        ',
  '+                    +        ',
  '+                    +        ',
  '+                    +        ',
  'X     t              X        ',
  '+          P         +        ',
  '+                    +        ',
  '+          -         +        ',
  '++++++++++++++++++++++++++++++'
 ],
 //made by Billy Anderson
 [
  '                    ',
  '     %%  %          ',
  '      % %%          ',
  '                    ',
  '      % %           ',
  '       %            ',
  '       %            ',
  '       %            ',
  '       %            ',
  '       %            ',
  '     %%%%%          ',
  '     %%%%%          ',
  '                    ',
  '                    ',
  '                    ',
  '@                  P',
  'bbbbbbbbbbbbbbbbbbbb'
 ],
 //continue my levels
  [
  '                    ',
  '                    ',
  '                    ',
  '                    ',
  '                    ',
  '                    ',
  '                    ',
  '                    ',
  '                    ',
  '                    ',
  '                    ',
  '                    ',
  '                    ',
  '                    ',
  '                    ',
  '  @                P',
  'bbbbbbZZZZZbbbbbbbbb'
 ],
 [
  '            χχ              ',
  '             χ              ',
  '             χ   @          ',
  '            Xχ   b          ',
  '                            ',
  '        X                   ',
  '                            ',
  '     X                      ',
  '                            ',
  '        X                   ',
  '                            ',
  '                            ',
  '    X                       ',
  '                            ',
  '                            ',
  ' X                          ',
  '     X            I         ',
  '                  I        P',
  '             X    χ    X   b',
  'ZZZZZZZZZZZZZZZZZZZZZZZZZZZZ'
 ],
 [
  '                                         ',
  '                                         ',
  '                                         ',
  '                                         ',
  '                                         ',
  '                                         ',
  '                                         ',
  '                                         ',
  '                                         ',
  '                                         ',
  '                         X               ',
  '                    X                    ',
  '              XXX                        ',
  '              XXX                        ',
  '              XXX                        ',
  '              XXX                        ',
  '              XXX                        ',
  '              XXX                        ',
  '              XXX                        ',
  '        X     XeX                        ',
  '              XMX                        ',
  'P    χ                           @       ',
  'b χ     X   XXXX                 -       ',
  'ZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZ'
 ],
 [
  '                              ',
  '                              ',
  '                              ',
  '                              ',
  '                              ',
  '                              ',
  '                              ',
  '                              ',
  '                              ',
  '                              ',
  '                              ',
  '                              ',
  '                              ',
  '                              ',
  '    %       %        %        ',
  '    %       %        %        ',
  '                              ',
  '                              ',
  '                              ',
  'P                             ',
  '       +        +      +     @',
  '- t    X  t     Xt     Xt tttb',
  'ZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZ'
 ],
 [
  '                                    ',
  '                                    ',
  '                                    ',
  '                                    ',
  '         %       %      %      %    ',
  '                                    ',
  '                                    ',
  '                                    ',
  '                                    ',
  '                                    ',
  '                                    ',
  '                                    ',
  '         X  &   &   &   X      X  X ',
  '                                  X ',
  '                                  X ',
  '                                  X ',
  '                                  X ',
  '                                  X ',
  '                                  X ',
  '                                  X ',
  '   Z                             XXX',
  '   Z                             XeX',
  '   Z                             XMX',
  ' @ Z  P       <     <               ',
  'bbbZ bb      X     X   A  A  V  AXXX',
  'ZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZ'
 ],
];